server.port=8081
spring.application.name=crossfit-drive

spring.datasource.url=jdbc:postgresql://localhost:5432/crossfit-drive
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
