server.port=8081
spring.application.name=crossfit-drive

spring.datasource.url=jdbc:postgresql://localhost:5432/crossfit-drive
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create

aws.region=a
aws.keys.access_key=a
aws.keys.secret_key=a
aws.bucket.name=a
spring.profiles.active=a