server.port=8085
spring.application.name=pedido

aws.region=us-east-2
aws.keys.access_key=AKIAW3MSMMA4ZHDDMSDQ
aws.keys.secret_key=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
aws.bucket.name=aws-treinamento3
spring.profiles.active=code402

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest